// Copyright 2024-2026 catitodev
// Licensed under the Apache License, Version 2.0
// SPDX-License-Identifier: Apache-2.0

//! Process and Network Baseline anomaly detection.
//!
//! Learns normal system behavior over a 7-day period and then detects
//! anomalies such as new processes, unusual parent-child relationships,
//! unexpected network connections, resource spikes, and data exfiltration.

use std::collections::{HashMap, HashSet};

use chrono::{DateTime, Duration, Utc};
use serde::{Deserialize, Serialize};

/// Duration of the learning period in days.
const LEARNING_PERIOD_DAYS: i64 = 7;

/// Exfiltration threshold: >300% of baseline volume.
const EXFILTRATION_THRESHOLD_PERCENT: f64 = 300.0;

/// Type of anomaly detected.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AnomalyType {
    /// A process not seen during the learning period.
    NewProcess,
    /// A process with an unusual parent process.
    UnusualParent,
    /// A process making unexpected network connections.
    UnexpectedNetwork,
    /// A process using significantly more resources than baseline.
    ResourceSpike,
    /// Data volume exceeds 300% of baseline (potential exfiltration).
    DataExfiltration,
    /// Connection to a destination never seen before.
    NewDestination,
    /// Regular periodic connections suggesting C2 beaconing.
    Beaconing,
}

/// An anomaly alert generated by the baseline system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AnomalyAlert {
    /// Type of anomaly detected.
    pub anomaly_type: AnomalyType,
    /// The entity that triggered the anomaly (process name, IP, etc.).
    pub entity: String,
    /// Details about the deviation from baseline.
    pub deviation_details: String,
    /// Severity of the anomaly (1-10).
    pub severity: u8,
    /// Recommended action.
    pub recommendation: String,
}

/// Learning state of a baseline system.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum BaselineLearningState {
    /// Currently learning normal behavior.
    Learning {
        /// When learning started.
        started_at: DateTime<Utc>,
        /// Days remaining in the learning period.
        days_remaining: u32,
    },
    /// Learning complete, actively detecting anomalies.
    Active,
    /// Baseline detection is disabled.
    Disabled,
}

/// Information about a process for baseline comparison.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProcessInfo {
    /// Process name.
    pub name: String,
    /// Parent process name.
    pub parent_name: Option<String>,
    /// PID of the process.
    pub pid: u32,
    /// Network connections made by this process.
    pub network_connections: Vec<String>,
    /// CPU usage percentage.
    pub cpu_percent: f64,
    /// Memory usage in bytes.
    pub memory_bytes: u64,
}

/// A network connection record for beaconing detection.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConnectionRecord {
    /// Process that made the connection.
    pub process: String,
    /// Destination address.
    pub destination: String,
    /// Destination port.
    pub port: u16,
    /// Timestamp of the connection.
    pub timestamp: DateTime<Utc>,
    /// Bytes transferred.
    pub bytes_transferred: u64,
}

/// Process baseline that learns and detects process anomalies.
pub struct ProcessBaseline {
    /// Current learning state.
    pub state: BaselineLearningState,
    /// Known process names observed during learning.
    pub known_processes: HashSet<String>,
    /// Known parent-child relationships (child -> set of known parents).
    pub parent_child_map: HashMap<String, HashSet<String>>,
    /// Known network patterns per process (process -> set of destinations).
    pub network_patterns: HashMap<String, HashSet<String>>,
    /// Resource usage baselines (process -> (avg_cpu, avg_memory)).
    pub resource_baselines: HashMap<String, (f64, u64)>,
    /// Sample counts for resource averaging.
    resource_sample_counts: HashMap<String, u64>,
}

impl ProcessBaseline {
    /// Creates a new process baseline and starts the learning period.
    pub fn new() -> Self {
        Self {
            state: BaselineLearningState::Learning {
                started_at: Utc::now(),
                days_remaining: LEARNING_PERIOD_DAYS as u32,
            },
            known_processes: HashSet::new(),
            parent_child_map: HashMap::new(),
            network_patterns: HashMap::new(),
            resource_baselines: HashMap::new(),
            resource_sample_counts: HashMap::new(),
        }
    }

    /// Creates a baseline that is already in Active state (for testing).
    pub fn new_active() -> Self {
        Self {
            state: BaselineLearningState::Active,
            known_processes: HashSet::new(),
            parent_child_map: HashMap::new(),
            network_patterns: HashMap::new(),
            resource_baselines: HashMap::new(),
            resource_sample_counts: HashMap::new(),
        }
    }

    /// Records a process observation during the learning period.
    pub fn learn(&mut self, process: &ProcessInfo) {
        if !matches!(self.state, BaselineLearningState::Learning { .. }) {
            return;
        }

        self.known_processes.insert(process.name.clone());

        if let Some(ref parent) = process.parent_name {
            self.parent_child_map
                .entry(process.name.clone())
                .or_default()
                .insert(parent.clone());
        }

        for conn in &process.network_connections {
            self.network_patterns
                .entry(process.name.clone())
                .or_default()
                .insert(conn.clone());
        }

        // Update running average for resources
        let count = self
            .resource_sample_counts
            .entry(process.name.clone())
            .or_insert(0);
        *count += 1;
        let n = *count as f64;

        let entry = self
            .resource_baselines
            .entry(process.name.clone())
            .or_insert((0.0, 0));
        // Incremental average
        entry.0 = entry.0 + (process.cpu_percent - entry.0) / n;
        entry.1 = ((entry.1 as f64) + (process.memory_bytes as f64 - entry.1 as f64) / n) as u64;
    }

    /// Updates the learning state based on elapsed time.
    pub fn update_state(&mut self) {
        if let BaselineLearningState::Learning { started_at, .. } = self.state {
            let elapsed = Utc::now() - started_at;
            if elapsed >= Duration::days(LEARNING_PERIOD_DAYS) {
                self.state = BaselineLearningState::Active;
            } else {
                let remaining = LEARNING_PERIOD_DAYS - elapsed.num_days();
                self.state = BaselineLearningState::Learning {
                    started_at,
                    days_remaining: remaining.max(0) as u32,
                };
            }
        }
    }

    /// Checks if a process is anomalous compared to the baseline.
    ///
    /// Returns `None` if the process is normal, or an `AnomalyAlert` if anomalous.
    /// Only active when state is `Active`.
    pub fn is_anomalous(&self, process: &ProcessInfo) -> Option<AnomalyAlert> {
        if !matches!(self.state, BaselineLearningState::Active) {
            return None;
        }

        // Check: new process
        if !self.known_processes.contains(&process.name) {
            return Some(AnomalyAlert {
                anomaly_type: AnomalyType::NewProcess,
                entity: process.name.clone(),
                deviation_details: format!(
                    "Process '{}' was not observed during the learning period",
                    process.name
                ),
                severity: 6,
                recommendation: "Investigate the origin of this process".to_string(),
            });
        }

        // Check: unusual parent
        if let Some(ref parent) = process.parent_name {
            if let Some(known_parents) = self.parent_child_map.get(&process.name) {
                if !known_parents.contains(parent) {
                    return Some(AnomalyAlert {
                        anomaly_type: AnomalyType::UnusualParent,
                        entity: process.name.clone(),
                        deviation_details: format!(
                            "Process '{}' spawned by unusual parent '{}'. Known parents: {:?}",
                            process.name, parent, known_parents
                        ),
                        severity: 7,
                        recommendation: "Check if the parent process is legitimate".to_string(),
                    });
                }
            }
        }

        // Check: unexpected network connections
        if let Some(known_conns) = self.network_patterns.get(&process.name) {
            for conn in &process.network_connections {
                if !known_conns.contains(conn) {
                    return Some(AnomalyAlert {
                        anomaly_type: AnomalyType::UnexpectedNetwork,
                        entity: process.name.clone(),
                        deviation_details: format!(
                            "Process '{}' connecting to unexpected destination: {}",
                            process.name, conn
                        ),
                        severity: 7,
                        recommendation: "Verify the network connection is authorized".to_string(),
                    });
                }
            }
        }

        // Check: resource spike
        if let Some(&(avg_cpu, avg_mem)) = self.resource_baselines.get(&process.name) {
            if avg_cpu > 0.0 && process.cpu_percent > avg_cpu * 3.0 {
                return Some(AnomalyAlert {
                    anomaly_type: AnomalyType::ResourceSpike,
                    entity: process.name.clone(),
                    deviation_details: format!(
                        "CPU usage {:.1}% exceeds baseline {:.1}% by >300%",
                        process.cpu_percent, avg_cpu
                    ),
                    severity: 5,
                    recommendation: "Monitor process for cryptomining or DoS activity"
                        .to_string(),
                });
            }
            if avg_mem > 0 && process.memory_bytes > avg_mem * 3 {
                return Some(AnomalyAlert {
                    anomaly_type: AnomalyType::ResourceSpike,
                    entity: process.name.clone(),
                    deviation_details: format!(
                        "Memory usage {} bytes exceeds baseline {} bytes by >300%",
                        process.memory_bytes, avg_mem
                    ),
                    severity: 5,
                    recommendation: "Check for memory leaks or malicious activity".to_string(),
                });
            }
        }

        None
    }
}

impl Default for ProcessBaseline {
    fn default() -> Self {
        Self::new()
    }
}

/// Network baseline that learns per-process network behavior.
pub struct NetworkBaseline {
    /// Current learning state.
    pub state: BaselineLearningState,
    /// Known destinations per process (process -> set of IPs/hosts).
    pub known_destinations: HashMap<String, HashSet<String>>,
    /// Data volume baselines per process-destination pair (key -> avg bytes).
    pub volume_baselines: HashMap<(String, String), u64>,
    /// Connection frequency baselines per process-destination (key -> connections per hour).
    pub frequency_baselines: HashMap<(String, String), f64>,
    /// Sample counts for volume averaging.
    volume_sample_counts: HashMap<(String, String), u64>,
}

impl NetworkBaseline {
    /// Creates a new network baseline and starts the learning period.
    pub fn new() -> Self {
        Self {
            state: BaselineLearningState::Learning {
                started_at: Utc::now(),
                days_remaining: LEARNING_PERIOD_DAYS as u32,
            },
            known_destinations: HashMap::new(),
            volume_baselines: HashMap::new(),
            frequency_baselines: HashMap::new(),
            volume_sample_counts: HashMap::new(),
        }
    }

    /// Creates a network baseline already in Active state (for testing).
    pub fn new_active() -> Self {
        Self {
            state: BaselineLearningState::Active,
            known_destinations: HashMap::new(),
            volume_baselines: HashMap::new(),
            frequency_baselines: HashMap::new(),
            volume_sample_counts: HashMap::new(),
        }
    }

    /// Records a connection during the learning period.
    pub fn learn(&mut self, record: &ConnectionRecord) {
        if !matches!(self.state, BaselineLearningState::Learning { .. }) {
            return;
        }

        self.known_destinations
            .entry(record.process.clone())
            .or_default()
            .insert(record.destination.clone());

        let key = (record.process.clone(), record.destination.clone());
        let count = self.volume_sample_counts.entry(key.clone()).or_insert(0);
        *count += 1;
        let n = *count as f64;

        let vol = self.volume_baselines.entry(key.clone()).or_insert(0);
        *vol = ((*vol as f64) + (record.bytes_transferred as f64 - *vol as f64) / n) as u64;
    }

    /// Checks if a connection represents potential data exfiltration (>300% baseline).
    pub fn check_exfiltration(
        &self,
        process: &str,
        dst: &str,
        bytes: u64,
    ) -> Option<AnomalyAlert> {
        if !matches!(self.state, BaselineLearningState::Active) {
            return None;
        }

        let key = (process.to_string(), dst.to_string());
        if let Some(&baseline_bytes) = self.volume_baselines.get(&key) {
            if baseline_bytes > 0 {
                let ratio = (bytes as f64 / baseline_bytes as f64) * 100.0;
                if ratio > EXFILTRATION_THRESHOLD_PERCENT {
                    return Some(AnomalyAlert {
                        anomaly_type: AnomalyType::DataExfiltration,
                        entity: process.to_string(),
                        deviation_details: format!(
                            "Process '{}' transferred {} bytes to {} (baseline: {} bytes, {:.0}% of baseline)",
                            process, bytes, dst, baseline_bytes, ratio
                        ),
                        severity: 8,
                        recommendation: "Investigate potential data exfiltration immediately"
                            .to_string(),
                    });
                }
            }
        }

        None
    }

    /// Checks if a process is connecting to a destination never seen during learning.
    pub fn check_new_destination(&self, process: &str, dst: &str) -> Option<AnomalyAlert> {
        if !matches!(self.state, BaselineLearningState::Active) {
            return None;
        }

        if let Some(known) = self.known_destinations.get(process) {
            if !known.contains(dst) {
                return Some(AnomalyAlert {
                    anomaly_type: AnomalyType::NewDestination,
                    entity: process.to_string(),
                    deviation_details: format!(
                        "Process '{}' connecting to new destination '{}' not seen during learning",
                        process, dst
                    ),
                    severity: 6,
                    recommendation: "Verify the destination is legitimate".to_string(),
                });
            }
        }

        None
    }

    /// Detects beaconing behavior: periodic connections at regular intervals.
    ///
    /// Analyzes connection timestamps for regularity. If the standard deviation
    /// of inter-connection intervals is less than 10% of the mean interval,
    /// it's considered beaconing.
    pub fn detect_beaconing(&self, connections: &[ConnectionRecord]) -> Option<AnomalyAlert> {
        if connections.len() < 3 {
            return None;
        }

        // Sort by timestamp and calculate intervals
        let mut timestamps: Vec<DateTime<Utc>> =
            connections.iter().map(|c| c.timestamp).collect();
        timestamps.sort();

        let intervals: Vec<f64> = timestamps
            .windows(2)
            .map(|w| (w[1] - w[0]).num_seconds() as f64)
            .collect();

        if intervals.is_empty() {
            return None;
        }

        let mean = intervals.iter().sum::<f64>() / intervals.len() as f64;
        if mean <= 0.0 {
            return None;
        }

        let variance =
            intervals.iter().map(|i| (i - mean).powi(2)).sum::<f64>() / intervals.len() as f64;
        let std_dev = variance.sqrt();

        // Beaconing: std_dev < 10% of mean (very regular intervals)
        let coefficient_of_variation = std_dev / mean;
        if coefficient_of_variation < 0.10 {
            let process = &connections[0].process;
            let destination = &connections[0].destination;
            return Some(AnomalyAlert {
                anomaly_type: AnomalyType::Beaconing,
                entity: process.clone(),
                deviation_details: format!(
                    "Process '{}' shows beaconing behavior to '{}': interval ~{:.0}s (CV: {:.3})",
                    process, destination, mean, coefficient_of_variation
                ),
                severity: 8,
                recommendation: "Investigate for C2 (Command & Control) communication"
                    .to_string(),
            });
        }

        None
    }
}

impl Default for NetworkBaseline {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_process_baseline_new_process_detected() {
        let mut baseline = ProcessBaseline::new_active();
        baseline.known_processes.insert("sshd".to_string());
        baseline.known_processes.insert("systemd".to_string());

        let unknown = ProcessInfo {
            name: "cryptominer".to_string(),
            parent_name: Some("bash".to_string()),
            pid: 1234,
            network_connections: vec![],
            cpu_percent: 5.0,
            memory_bytes: 1024,
        };

        let alert = baseline.is_anomalous(&unknown);
        assert!(alert.is_some());
        assert_eq!(alert.unwrap().anomaly_type, AnomalyType::NewProcess);
    }

    #[test]
    fn test_process_baseline_unusual_parent() {
        let mut baseline = ProcessBaseline::new_active();
        baseline.known_processes.insert("bash".to_string());
        let mut parents = HashSet::new();
        parents.insert("sshd".to_string());
        baseline.parent_child_map.insert("bash".to_string(), parents);

        let process = ProcessInfo {
            name: "bash".to_string(),
            parent_name: Some("cron".to_string()), // unusual parent
            pid: 5678,
            network_connections: vec![],
            cpu_percent: 1.0,
            memory_bytes: 512,
        };

        let alert = baseline.is_anomalous(&process);
        assert!(alert.is_some());
        assert_eq!(alert.unwrap().anomaly_type, AnomalyType::UnusualParent);
    }

    #[test]
    fn test_process_baseline_resource_spike() {
        let mut baseline = ProcessBaseline::new_active();
        baseline.known_processes.insert("nginx".to_string());
        baseline
            .resource_baselines
            .insert("nginx".to_string(), (5.0, 100_000));

        let process = ProcessInfo {
            name: "nginx".to_string(),
            parent_name: None,
            pid: 100,
            network_connections: vec![],
            cpu_percent: 95.0, // Way above 5.0 * 3 = 15.0
            memory_bytes: 100_000,
        };

        let alert = baseline.is_anomalous(&process);
        assert!(alert.is_some());
        assert_eq!(alert.unwrap().anomaly_type, AnomalyType::ResourceSpike);
    }

    #[test]
    fn test_network_baseline_exfiltration() {
        let mut baseline = NetworkBaseline::new_active();
        baseline
            .volume_baselines
            .insert(("curl".to_string(), "api.example.com".to_string()), 1000);

        // 4000 bytes = 400% of baseline (> 300% threshold)
        let alert = baseline.check_exfiltration("curl", "api.example.com", 4000);
        assert!(alert.is_some());
        assert_eq!(alert.unwrap().anomaly_type, AnomalyType::DataExfiltration);
    }

    #[test]
    fn test_network_baseline_new_destination() {
        let mut baseline = NetworkBaseline::new_active();
        let mut known = HashSet::new();
        known.insert("api.example.com".to_string());
        baseline
            .known_destinations
            .insert("curl".to_string(), known);

        let alert = baseline.check_new_destination("curl", "evil.example.com");
        assert!(alert.is_some());
        assert_eq!(alert.unwrap().anomaly_type, AnomalyType::NewDestination);
    }

    #[test]
    fn test_network_baseline_no_alert_known_destination() {
        let mut baseline = NetworkBaseline::new_active();
        let mut known = HashSet::new();
        known.insert("api.example.com".to_string());
        baseline
            .known_destinations
            .insert("curl".to_string(), known);

        let alert = baseline.check_new_destination("curl", "api.example.com");
        assert!(alert.is_none());
    }

    #[test]
    fn test_beaconing_detection() {
        let base_time = Utc::now();
        // Create connections at very regular 60-second intervals
        let connections: Vec<ConnectionRecord> = (0..10)
            .map(|i| ConnectionRecord {
                process: "malware".to_string(),
                destination: "c2.evil.com".to_string(),
                port: 443,
                timestamp: base_time + Duration::seconds(i * 60),
                bytes_transferred: 100,
            })
            .collect();

        let baseline = NetworkBaseline::new_active();
        let alert = baseline.detect_beaconing(&connections);
        assert!(alert.is_some());
        let alert = alert.unwrap();
        assert_eq!(alert.anomaly_type, AnomalyType::Beaconing);
        assert!(alert.deviation_details.contains("malware"));
    }

    #[test]
    fn test_no_beaconing_irregular_connections() {
        let base_time = Utc::now();
        // Create connections at irregular intervals
        let intervals = [5, 120, 3, 300, 15, 60, 2, 180];
        let mut connections = Vec::new();
        let mut offset = 0i64;
        for &interval in &intervals {
            connections.push(ConnectionRecord {
                process: "browser".to_string(),
                destination: "various.com".to_string(),
                port: 443,
                timestamp: base_time + Duration::seconds(offset),
                bytes_transferred: 500,
            });
            offset += interval;
        }

        let baseline = NetworkBaseline::new_active();
        let alert = baseline.detect_beaconing(&connections);
        assert!(alert.is_none());
    }

    #[test]
    fn test_learning_state_transition() {
        let mut baseline = ProcessBaseline {
            state: BaselineLearningState::Learning {
                started_at: Utc::now() - Duration::days(8),
                days_remaining: 0,
            },
            known_processes: HashSet::new(),
            parent_child_map: HashMap::new(),
            network_patterns: HashMap::new(),
            resource_baselines: HashMap::new(),
            resource_sample_counts: HashMap::new(),
        };

        baseline.update_state();
        assert_eq!(baseline.state, BaselineLearningState::Active);
    }
}
