// Copyright 2024-2026 catitodev
// Licensed under the Apache License, Version 2.0
// SPDX-License-Identifier: Apache-2.0

//! D-Bus interface definitions for communication between Backend_API and Privileged_Daemon.

use serde::{Deserialize, Serialize};

/// The well-known D-Bus bus name for the Privileged Daemon.
pub const DBUS_BUS_NAME: &str = "org.securitycommandcenter.Privileged";

/// The D-Bus object path for the Privileged Daemon.
pub const DBUS_OBJECT_PATH: &str = "/org/securitycommandcenter/Privileged";

/// The D-Bus interface name for the Privileged Daemon.
pub const DBUS_INTERFACE_NAME: &str = "org.securitycommandcenter.Privileged";

/// List of all D-Bus method names exposed by the Privileged Daemon.
/// Used for whitelist validation and documentation.
pub const DBUS_METHODS: &[&str] = &[
    "StartTool",
    "StopTool",
    "RestartTool",
    "ApplyFirewallRule",
    "RemoveFirewallRule",
    "BlockIP",
    "ApproveUSBDevice",
    "BlockUSBDevice",
    "QuarantineFile",
    "RestoreFromQuarantine",
    "DeleteQuarantined",
    "CreateSnapshot",
    "RollbackSnapshot",
    "EnforceMACProfile",
    "CaptureForensicsSnapshot",
    "TraceProcess",
    "VerifyIntegrity",
];

/// Signal types emitted by the Privileged Daemon.
pub mod signals {
    use super::*;

    /// Alert generated by a security tool.
    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub struct AlertGenerated {
        pub alert_json: String,
    }

    /// A tool's status has changed.
    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub struct ToolStatusChanged {
        pub tool_name: String,
        pub new_status: String,
    }

    /// A canary token was triggered.
    #[derive(Debug, Clone, Serialize, Deserialize)]
    pub struct CanaryTriggered {
        pub canary_json: String,
    }
}
